site_name: Ultrakill Modding Wiki
plugins:
  - search
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
  favicon: assets/images/favicon.png
  icon:
    admonition:
      warning: material/alert
  palette: 
    scheme: slate
    primary: black
    accent: deep orange
  
  logo: assets/images/ultrakill.png
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details