site_name: Ultrakill Modding Wiki
plugins:
  - search
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
  favicon: assets/images/favicon.png
  palette: 
    scheme: slate
    primary: black
    accent: deep orange
  
  logo: assets/images/ultrakill.png